exclude_re = [
  'src/convert\.rs:\d+:\d+: replace && with \|\| in parse_gep',
  'src/convert\.rs:\d+:\d+: replace > with >= in parse_gep',
  'src/convert\.rs:\d+:\d+: replace > with == in parse_gep',
  'src/convert\.rs:\d+:\d+: replace > with < in parse_gep',
  'src/convert\.rs:\d+:\d+: replace > with >= in process_ir_defined_q_fns',
  'src/convert\.rs:\d+:\d+: delete ! in parse_gep',
  'src/bin/stub_gen\.rs:\d+:\d+: replace main -> Result<\(\)> with Ok\(\(\)\)',
  'src/main\.rs:\d+:\d+: replace main with \(\)',
  'src/lib\.rs:\d+:\d+: replace aux::validate_module_layout_and_triple with \(\)',
  'src/lib\.rs:\d+:\d+: delete ! in aux::validate_module_layout_and_triple',
  'src/lib\.rs:\d+:\d+: replace && with \|\| in aux::validate_functions',
  'src/lib\.rs:\d+:\d+: replace != with == in aux::process_call_instruction',
  'src/lib\.rs:\d+:\d+: delete match arm "___get_wasm_context" in aux::handle_qtm_call',
  'src/lib\.rs:\d+:\d+: replace == with != in aux::handle_mz_call',
  'src/lib\.rs:\d+:\d+: replace get_wasm_functions -> .*',
  'src/llvm_verify\.rs:\d+:\d+: replace == with != in verify_module',
  'src/opt\.rs:\d+:\d+: replace > with >= in optimize',
  'src/opt\.rs:\d+:\d+: replace > with == in optimize',
  'src/opt\.rs:\d+:\d+: replace > with < in optimize',
  'src/opt\.rs:\d+:\d+: delete match arm 1 in optimize',
  'src/opt\.rs:\d+:\d+: delete match arm 3 in optimize',
]
