name: Typos
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: crate-ci/typos@v1.48.0
